[book]
authors = ["Théo Tchilinguirian"]
language = "en"
multilingual = false
src = "src"
title = "A concise guide to APT"

[output.html]
git-repository-url = "https://github.com/theotchlx/apt-guide"

